# This workflow will install Python dependencies, run tests and 
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Unitest
      run: python -m unittest discover tests
    
  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:  
    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build image
      run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/python-app-github-actions:latest
    - name: Push image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/python-app-github-actions:latest
